### PR TITLE
ammo stacking i suppose

### PR DESCRIPTION
**Pull request by Pengu1ns**
idk if its one to one but you get the idea

### CODE REVIEW

**Comment by Milxnor** [comment]
ok so i dont know if they actually do this or if the pickups combine (like when u drop two near eachother)

**Comment by Pengu1ns** [comment]
depends if other servers that have this working have pickup combining idk

**Comment by Milxnor** [comment]
i dont think any other server even has it where on playground and stuff it drops the extra ammo and stuff thats proper proper looting. and no gs has pickupc ombining i meani have it but there are rare bugs with it.

**Comment by Pengu1ns** [comment]
i think other game servers combine the extra ammo bc you also cant see it drop seperate if you look at youtube videos

**Comment by Milxnor** [comment]
read what i said, no gameserver has it even spawning multiple stacks because their looting is a bit scuffed

**Pull request closed without merging**
