### PR TITLE
Small fix for the fortilla not being on the water level

### PR DESCRIPTION
**Pull request by MarvelcoOGFN**
ik you may have closed this before but it does work (if you think i used paks i didnt)

### CODE REVIEW

**Comment by max8447** [comment]
it really doesnt

**Comment by MarvelcoOGFN** [comment]
image
see it does
@max8447

**Comment by MarvelcoOGFN** [comment]
cause max doesnt agree ig

**Comment by max8447** [comment]
and lintu
and fortnite

**Comment by IzTendo** [comment]
https://github.com/Milxnor/Project-Reboot-3.0/assets/25051222/4e29ddaf-62b8-487b-a2ce-f35ff060a6ca

This isn't even a disagreement, it's simply scuffed, barely functional code and has zero reason to be pushed.

If you're going to "fix" something, actually go through the effort and fix the entire thing. Saying it's "someone else's problem" won't get you anywhere.

**Comment by MarvelcoDev** [comment]
> 8mb.video-NK9-ck1UD8Vk.mp4 
> This isn't even a disagreement, it's simply scuffed, barely functional code and has zero reason to be pushed.
> 
> If you're going to "fix" something, actually go through the effort and fix the entire thing. Saying it's "someone else's problem" won't get you anywhere.

if you see what i changed it has nothing to do with the poi

**Comment by IzTendo** [comment]
> > 8mb.video-NK9-ck1UD8Vk.mp4
> > This isn't even a disagreement, it's simply scuffed, barely functional code and has zero reason to be pushed.
> > If you're going to "fix" something, actually go through the effort and fix the entire thing. Saying it's "someone else's problem" won't get you anywhere.
> 
> if you see what i changed it has nothing to do with the poi

No need to continue proving that you're stupid, just move on. :)

**Pull request closed without merging**
