### PR TITLE
bosses and fixes

### PR DESCRIPTION
**Pull request by Project-Z1K**

### CODE REVIEW

**Comment by Project-Z1K** [comment]
i alr made the fixed check last update the firs is bosses the fortplayercontoller.cpp

**Comment by Project-Z1K** [comment]
trying to fix the s14 buggy on the surfer wepon but i dont think is working

**Comment by MarvelcoDev** [comment]
bro you cant even compile this :skull:

**Comment by Project-Z1K** [comment]
Ik i need to push all or my src wait Bro xd

**Comment by MarvelcoDev** [comment]
> Ik i need to push all or my src wait Bro xd

why did you deleted it?

**Comment by max8447** [comment]
youre elw, right?

**Comment by Twin1dev** [comment]
hes a paster who just copies other pull req

**Comment by plooshi** [comment]
bro pasted my code

**Comment by Project-Z1K** [comment]
ploosh i didint paste it u didint made it stuff up and stop rat pepole using ur pasted eon

**Comment by plooshi** [comment]
??? i killed astro and i dont rat. AND THIS IS MY CODE AND I CAN TELL

> ploosh i didint paste it u didint made it stuff up and stop rat pepole using ur pasted eon

**Comment by plooshi** [comment]
i know my own variable names and i am probably the only one to debug like this :skull:
image

**Comment by max8447** [comment]
💀 if you didnt know Project-Z1K is a big skidder. he changes his name all the time, cant speak proper english and always tries to sell other people's code as his. dont trust a word he says

**Comment by plooshi** [comment]
i know and i'm trying to defend myself as it's my code

**Comment by Project-Z1K** [comment]
> 💀 if you didnt know Project-Z1K is a big skidder. he changes his name all the time, cant speak proper english and always tries to sell other people's code as his. dont trust a word he says

i never sell stuff i better than u mf paster and ploosh is the worst ratter he got exposed in yt videos poofs and all and u just skkiding reboot 24/7 my paster

**Comment by plooshi** [comment]
.

**Comment by plooshi** [comment]
image
AHEM AHEM

**Comment by plooshi** [comment]
you literally cannot defend yourself against that one

**Comment by plooshi** [comment]
and no i dont rat it was my stupid friend who i have blocked now bc of that

**Comment by max8447** [comment]
> image AHEM AHEM

LMFAO

**Comment by Project-Z1K** [comment]
LMAO TO THIS YES OFC I NOT GOING TO LEAK MY GS MORE EASY USE UR PASTE ASS REMAKE MADED BY ARAY0X LLLLLL SKKIDDDDDDDDDDDDDDDDDDDDDDDDDD

**Comment by max8447** [comment]
bud instead of yapping 24/7 try to have one name for more than a week, and PLEASE learn proper english

**Comment by Project-Z1K** [comment]
max stop paste and skkid reboot

**Comment by plooshi** [comment]
you literally cant deny it, it literally has my fucking name in the class :sob:

**Comment by Project-Z1K** [comment]
Ye ik the open src as i tell u not going to leak my imgui w gs self made lol working s12 and 13 for ass open src i just paste ur skkid  src

**Comment by UWUFN** [comment]
i can 100% confirm you have never made anything. you even skidded my shit and i’m barely even a dev 😭 nothing on your page is original. your latest repo is literally a youtube battleship console tutorial and you wrote the youtube shit and left it there ☠️☠️

**Comment by plooshi** [comment]
> Ye ik the open src as i tell u not going to leak my imgui w gs self made lol working s12 and 13 for ass open src i just paste ur skkid src

leak your pasted imgui? and you cant do shit for yourself with your shitty english. please, go back to kindergarten.

**Comment by GDBOI101** [comment]
RepoForker1000 vs LithiumGS vs EonFallOff feat. Carbon Stan and Beyond (The Poles)

This is peak Fortnite Modding

**Comment by Project-Z1K** [comment]
LMAO u forgot ploosh ratting pepole on hes ass pasted eon launcher and gs

**Comment by UWUFN** [comment]
> RepoForker1000 vs LithiumGS vs EonFallOff feat. Carbon Stan and Beyond (The Poles)
> 
> This is peak Fortnite Modding

when are we getting the shieldmp and waybackgs update??

**Comment by Project-Z1K** [comment]
in 8029

**Comment by Project-Z1K** [comment]
wtf is shieldmp ?

**Comment by itztiva** [comment]
skid z1k!

**Comment by GDBOI101** [comment]
Ngl I think he might be worse than Cinar.

**Comment by itztiva** [comment]
this kid is so down bad bro all his repos are legit skidded

**Comment by Project-Z1K** [comment]
lmao no are not i can code better than u i have alot tuts i post in yt how to update chairs make fix esp code ur own and more i made alot games in c# there are in my github no skkid anybody have it LMAO ur just a ploosh all ratting pepole using astro fn

**Comment by MarvelcoDev** [comment]
> lmao no are not i can code better than u i have alot tuts i post in yt how to update chairs make fix esp code ur own and more i made alot games in c# there are in my github no skkid anybody have it LMAO ur just a ploosh all ratting pepole using astro fn

ok bro you are a known skidder no one believes any shit that you "code" cause everysingle thing is pasted also please fix your english

**Comment by Project-Z1K** [comment]
daddy stop skkid eon launcher and WOMP WOMP

**Comment by GDBOI101** [comment]
https://github.com/GDBOI101/WaybackGS/pull/9#issuecomment-2067789749

Imgui leaker gs

**Comment by Project-Z1K** [comment]
?? its true btw i make my own shit lol i can proof it

**Comment by Project-Z1K** [comment]
i just want to be friend not be mad

**Comment by Project-Z1K** [comment]
but all of u are just retarded toxic or just rat pepole like ploosh

**Comment by itztiva** [comment]
we arent? and also ploosh doesnt rat lmao

**Comment by Project-Z1K** [comment]
bro u want me to send proofs here

**Comment by Project-Z1K** [comment]
he is exposed in all servers lol

**Comment by Project-Z1K** [comment]
1.8 and 1,9 1,9,1 gs maded by me @GDBOI101 


image

**Comment by Project-Z1K** [comment]
basic imgui

**Comment by Project-Z1K** [comment]
1.9.1

image

**Comment by Project-Z1K** [comment]
image

**Comment by UWUFN** [comment]
BRO I RECOGNIZE THAT UI THATS KPARSERS 1.7.2 MODIFIED UI

**Comment by Project-Z1K** [comment]
YES OFC ALL THE UI ARE THE SAME IF U DONT ADD STILES LOL BUT U CAN SEE I ON 1.9.1 CHECK THE MAP LOLLLLLLLLL MY S14 13 12 HAVE SAME MENU LOLLLLLLLLLLLLLLLL L SKKID U ARE UWUFN

**Comment by itztiva** [comment]
dude your a skid just admit it kid

**Comment by UWUFN** [comment]
nigga just dry snitched on himself sayin he ain’t make shit . u js proved ur point that ur a paster n a skidder ☠️☠️ give it up dawg

**Comment by Project-Z1K** [comment]
lmao nice eng

**Comment by Project-Z1K** [comment]
bro u cant code @UWUFN check ur ass pasted sulfure 6.10 u cant ever fix it bc u cant code so stuff

**Comment by UWUFN** [comment]
> bro u cant code @UWUFN check ur ass pasted sulfure 6.10 u cant ever fix it bc u cant code so stuff

u yappin a whole bunch of nonsense u the same nigga who forked it twice tryna fix it . it wasnt even a working gameserver, it was a base me n jagger worked on for like 3 days . shit was not a real project at all it was some shit for fun . YOU cannot code at all

**Comment by Project-Z1K** [comment]
no is not u was selling this pasted but u cant code so u never get it working u dont know how to make working listening this is why u dont update the src go learn mr skkid

**Comment by Project-Z1K** [comment]
and btw i fix it i using it rn adding abilityes and more

**Comment by UWUFN** [comment]
i was not selling JACKSHIT, thank you very much lmao . ain touch that repo since the last update, the listening works just fine . ik damn well u ain add shit u dont even kno shit, milxnor even touched the src n didnt even bother . im not updatin the src cs i dont care for it n its not real shit anyways, it wasnt ever meant to be a thing

**Comment by MrJohnson2-0** [comment]
> bro u cant code @UWUFN check ur ass pasted sulfure 6.10 u cant ever fix it bc u cant code so stuff

Bro i'm sorry but you deadass cant call bro a paster when its not forked or anything. That's not how pasting works. It has to be a previous repo. All his shit was original, sorry to tell you. Jaysen is not a skidder and in fact is prob one of the least retarded people in reboot

**Comment by Project-Z1K** [comment]
> i was not selling JACKSHIT, thank you very much lmao . ain touch that repo since the last update, the listening works just fine . ik damn well u ain add shit u dont even kno shit, milxnor even touched the src n didnt even bother . im not updatin the src cs i dont care for it n its not real shit anyways, it wasnt ever meant to be a thing

hell nah i fix it bc the code is weird for listening and all lol and dont lie ur a alt of JACK yall know it and u dont update it bc u cant fix it

**Comment by UWUFN** [comment]
1. who the hell is jack
2. listening code works just fine, it’s not weird but it isn’t proper listening either, it’s listening from 2022
3. i don’t update it bc there’s 0 need to update it, it was a learning project and i know what i need to know now . the shit in there is unfixable due to a shit base being used bud

**Comment by Project-Z1K** [comment]
dont lie u dont update bc cant code

**Comment by UWUFN** [comment]
fuk i gotta lie to some pakistanian 14 yr old abt my online abilities for? there’s 0 reason to continue working on that shit
IMG_0109
IMG_0110
IMG_0119
IMG_0120
IMG_0121
IMG_0122
IMG_0123

**Comment by Project-Z1K** [comment]
image
HAHAAHAHAH THIS IS NOT ME LMAOOOOOOOOOO

**Comment by Project-Z1K** [comment]
JAYSEN ALT UR SO DUMP

**Comment by UWUFN** [comment]
that’s literally you + this is my main github

**Comment by Project-Z1K** [comment]
nah hell

**Comment by Ralzify** [comment]
> image HAHAAHAHAH THIS IS NOT ME LMAOOOOOOOOOO

you're the only person who doesn't know english and would type like this...

**Comment by Project-Z1K** [comment]
nah i not the only one there is more than 20m of pepole lmao and ye i cant speak this is why i speking rn a i tu no sabes Español asi que por esa regla de 3 ves a chuparla putita

**Comment by Project-Z1K** [comment]
skkiding reboot saying u add fixesb

**Comment by UWUFN** [comment]
somebody js hit the language switch on this nigga mid message im crine ☠

**Comment by Ralzify** [comment]
> somebody js hit the language switch on this nigga mid message im crine ☠

LMFAOOO

**Comment by max8447** [comment]
> nah i not the only one there is more than 20m of pepole lmao and ye i cant speak this is why i speking rn a i tu no sabes Español asi que por esa regla de 3 ves a chuparla putita

holy fuck do you even know what context is???

**Comment by Project-Z1K** [comment]
bro ur weird stop talk on a poll and go dms on disc If you have eggs

**Comment by Project-Z1K** [comment]
real eggs

**Comment by max8447** [comment]
brother even if i wanted to argue with you in dms i wouldnt know who the fuck to dm cuz you change your name 24/7

**Comment by max8447** [comment]
also mf youre the one who started like

**Comment by Project-Z1K** [comment]
nah i didint was ploosh and hes ratted launcher

**Comment by Project-Z1K** [comment]
saying i paste hes bosses code when i didint paste hes bosses is ms code for bosses in s13 lol

**Pull request closed without merging**
