### PR TITLE
Added auto restart (temporay method)

### PR DESCRIPTION
**Pull request by zazdev123**
Added automatic restart, temporary method that displays the top 1 for a few seconds and restarts automatically

### CODE REVIEW

**Comment by Finninn** [comment]
Restart method doesn’t work iirc

**Comment by zazdev123** [comment]
working for me in 5.00/5.01

**Comment by Finninn** [comment]
> working for me in 5.00/5.01

I’m stupid I thought this was Forge lmao, ignore my message

**Comment by Milxnor** [comment]
> That jawn would only work in solos

ong bruh also liek auto restart is in there it worked at one point ill re-add it eventually idk if it works still i just was messin w/ bots

**Pull request closed without merging**
