### PR TITLE
add loot spawning after breaking under chest

### PR DESCRIPTION
**Pull request by NotJeppy**
also fix ItemsToDropoOffset -> ItemsToDropOffset

### CODE REVIEW

**Comment by NotJeppy** [comment]
sorry for the include spam I was tired and copied everything from the file I needed

**Comment by Milxnor** [comment]
this so scufed bro ill merge it maybe im thinking about it

**Comment by NotJeppy** [comment]
> this so scufed bro ill merge it maybe im thinking about it

I know bro but that's how I think unfortunately. Feel free to make a followup push to remove the unnecessary stuff lol

**Comment by max8447** [comment]
I think the actual func is abuildingcontainer::bp_spawnloot

**Pull request closed without merging**
