### PR TITLE
real fix for water level

### PR DESCRIPTION
**Pull request by MarvelcoOGFN**

### CODE REVIEW

**Comment by Milxnor** [comment]
what

**Comment by MarvelcoOGFN** [comment]
> what

I did fix it ask hax

**Comment by MarvelcoOGFN** [comment]
It worked no pak

**Comment by max8447** [comment]
only issue is that it isnt a fix

**Comment by max8447** [comment]
youre just giving it another reason to crash if it somehow gets called with an invalid value

**Comment by MarvelcoOGFN** [comment]
> only issue is that it isnt a fix

Pls ask hax he will te you

**Pull request closed without merging**
