### PR TITLE
Some Event Fixes, 18.10 Crash fix, random crash after a few minutes for s17+

### PR DESCRIPTION
**Pull request by ILoveTacosFromJITB**

### CODE REVIEW

**Comment by UnNyanCat** [comment]
what is 17+ crash fix ?

**Comment by ILoveTacosFromJITB** [comment]
It's a fix for the server crash that happens after a few minutes of hosting for chapter 2 season 7 and chapter 2 season 8

**Comment by UnNyanCat** [comment]
ye but where is it?

**Comment by ILoveTacosFromJITB** [comment]
it's in dllmain.cpp

**Comment by Milxnor** [comment]
whats your discord

**Comment by max8447** [comment]
while youre at it give me my forge role back too

**Comment by UnNyanCat** [comment]
you dont need it

**Comment by UnNyanCat** [comment]
(IM JOKING)

**Comment by ILoveTacosFromJITB** [comment]
flimsypenguin, i'm in the reboot discord

**Pull request merged**
