### PR TITLE
Fixes and improvements

### PR DESCRIPTION
**Pull request by KedisPL**
I decided to fix some things, and also to improve. I plan to add more things in the future.

### CODE REVIEW

**Comment by KedisPL** [comment]
I will try to fix water level in 13.40 later, also some other stuff.

**Comment by Milxnor** [comment]
this dont fix vehicle replication on s13+ thats why vehicle spawning was disabled, use another client and youll see.

**Comment by KedisPL** [comment]
alright

**Comment by KedisPL** [comment]
So I did some testing on 2 clients. On the client that is driving the car it seems to be working fine, and on the other client there are problems with the rotation of the vehicle, but otherwise it works fine. Here is the video (sorry for the lag, but my processor couldn't handle 3 Fortnite's launched at the same time (Most of car teleporting are due to this, I might test it with somone on other pc later)): https://youtu.be/RdJNQDrH2kg

**Comment by KedisPL** [comment]
https://youtu.be/vglxVw6IE0E I tested with another person.

**Comment by Milxnor** [comment]
> So I did some testing on 2 clients. On the client that is driving the car it seems to be working fine, and on the other client there are problems with the rotation of the vehicle, but otherwise it works fine. Here is the video (sorry for the lag, but my processor couldn't handle 3 Fortnite's launched at the same time (Most of car teleporting are due to this, I might test it with somone on other pc later)): https://youtu.be/RdJNQDrH2kg

yes i know that but rotation can cause random deaths and such

**Comment by KedisPL** [comment]
> yes i know that but rotation can cause random deaths and such

Deaths, random exiting of the vehicle and falling off the map I have already fixed.

**Comment by KedisPL** [comment]
> > yes i know that but rotation can cause random deaths and such
> 
> Deaths, random exiting of the vehicle and falling off the map I have already fixed.

I tested on: 13.40, 14.60, 17.50, 18.40
Only once when I spawned a car on the helicarrier (14.60) did I fall under the floor.

**Comment by max8447** [comment]
> > yes i know that but rotation can cause random deaths and such
> 
> Deaths, random exiting of the vehicle and falling off the map I have already fixed.

did you include it in this pr? i know this pr is already closed but i'd still like to look at it

**Comment by KedisPL** [comment]
Yes, I may send that code to you later. It's just one line of code.

**Pull request closed without merging**
